---
resources:
- name: pcf-attendee-service-code
  type: git
  source:
    uri: https://github.com/PrasanthMohanCognizant/pcf-attendee-service-code
    branch: master

- name: deploy-attendee-service
  type: cf
  source:
    api: https://api.system.cumuluslabs.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: pmohan-PAL-Dec11
    space: sandbox
    skip_cert_check: true

jobs:
- name: test
  public: true
  plan:
  - get: pcf-attendee-service-code
    trigger: true
  - task: test
    file: pcf-attendee-service-code/ci/tasks/test.yml

- name: deploy
  public: true
  plan:
  - get: pcf-attendee-service-code
    trigger: true
    passed: [test]
  - task: package
    file: pcf-attendee-service-code/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: pcf-attendee-service-code/manifest.yml
      path: package-output/attendee-service.jar

- name: smoke_test
  public: true
  plan:
  - get: pcf-attendee-service-code
    trigger: true
    passed: [deploy]
  - task: smoke_test
    file: pcf-attendee-service-code/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: attendee-service-dasyuroid-linalool.apps.cumuluslabs.io
